### PR TITLE
file restructure

### LINKED ISSUE #24: file structure is quite confusing
isn't it confusing to tell students to start in step 1 folder and continue working in step 1 folder even when we move on to step 2?

maybe have step 1 as the root, then the other steps in the walkthrough steps folder?

### PR DESCRIPTION
**Pull request by mattlub**
fixes #24, #27 

- moves the contents of the `walkthroughSteps/step-1/` folder into the root of the project. Now students can clone the repo and work in the root of the project. Before they worked inside the `step-1` folder, or in Nazareth, they were working off a branch (skeleton) which had implemented this same change anyway.
- Removes two unused lines from `src/handler`
- removes defunct extra `package.json` and empty `data.sql` file
- adds a note to the mentor notes file

### CODE REVIEW

**Comment by shiryz** [comment]
@mattlub since you're already working on this, I am still keen to get the skeleton branch merged, it is unnecessary to have to build the server and get data from static files when it'll be removed later
Opened [this issue](https://github.com/foundersandcoders/master-reference/issues/893) a long time ago

**Comment by mattlub** [comment]
@shiryz this PR is effectively doing the same thing as the skeleton branch, i.e. moving files from `step-1` folder into the root

**Comment by shiryz** [comment]
@mattlub you can ignore my comment :sweat_smile:, for some reason I thought it didn't have the server

**Comment by mattlub** [comment]
@shiryz no worries! 😄 :shipit:

**Review by eliasmalik — APPROVED** [review]
@mattlub any chance the insecure dependencies can be taken care of with this PR too?

**Comment by mattlub** [comment]
@eliascodes I can do it in another PR

**Comment by m4v15** [comment]
@developess can we go ahead and merge this and then we can look at yours (as this one is smaller)

**Comment by m4v15** [comment]
merging as @developess said it was ok 😄

**Pull request merged**
